language: cpp
branches:
  only:
    - master
compiler:
  - gcc
addons:    
  sources:
    - ubuntu-toolchain-r-test
 apt:
   packages:
    - g++-6 
    - gcc-6     
    - doxygen

before_script:
  # Link gcc-6 and g++-6 to their standard commands
  - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  #install google-test
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake # install cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - sudo mkdir /usr/local/lib/gtest
  - sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
  - sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a

  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - cd $TRAVIS_BUILD_DIR
script:  
  - cmake .
  - cmake --build .
  - cmake --build . --target package
  - doxygen Doxyfile
  - ./test/tb_print_ip
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T prj_print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ucdandrey:$BINTRAY_API_KEY "https://api.bintray.com/content/cda/otus-cpp/prj_print_ip/$TRAVIS_BUILD_NUMBER/prj_print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master