language: cpp
branches:
  only:
    - master
#before_install:
#- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#- sudo apt-get update -qq
#
#install:
#- sudo apt-get install -qq g++-10
#- export CXX="g++-10"
matrix:
  include:
# GCC 7 c++17 
    - env: COMPILER=g++-7 BUILD_TYPE=Debug GSL_CXX_STANDARD=17
      addons: *gcc7

    - env: COMPILER=g++-7 BUILD_TYPE=Release GSL_CXX_STANDARD=17
      addons: *gcc7
install:
  # Set the ${CXX} variable properly
  - export CXX=${COMPILER}
  - ${CXX} --version

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Travis machines have 2 cores
  - JOBS=2

addons:    
 apt:
    packages:
      - doxygen

before_script:
  #install google-test
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake # install cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - sudo mkdir /usr/local/lib/gtest
  - sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
  - sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a

  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - cd $TRAVIS_BUILD_DIR
script:  
  - cmake .
  - cmake --build .
  - cmake --build . --target package
  - doxygen Doxyfile
  - ./test/tb_print_ip
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T prj_print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ucdandrey:$BINTRAY_API_KEY "https://api.bintray.com/content/cda/otus-cpp/prj_print_ip/$TRAVIS_BUILD_NUMBER/prj_print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master